### ISSUE TITLE
Static or initial files should be located in the "bwapi-data/AI/" folder not the "bwapi-data/read/" folder

### ISSUE THREAD

**Issue by chriscoxe** [Ravaelles/Atlantis#4]
Static files should be located in the "bwapi-data/AI/" folder not the "bwapi-data/read/" folder.  Similarly for the initial version of files that are initially read the first time the bot is run (e.g. initial configuration of build orders) then written by the bot as new versions (e.g. adaptation of build orders for particular opponents).  The static/initial files should reside in the "bwapi-data/AI/" folder and new versions of them (if applicable) should reside in the "bwapi-data/read/" and "bwapi-data/write/" folders for reading or writing respectively. The reason is for compatibility with [StarcraftAITournamentManager](https://github.com/davechurchill/StarcraftAITournamentManager) which is used in some of the annual competitions like AIIDE and CIG.  If this is not done, I think the build order config files could fail to load because they may be missing.

I.E. the [AIIDE Rules page](https://webdocs.cs.ualberta.ca/~cdavid/starcraftaicomp/rules.shtml) mentions this about the "bwapi-data/read/"folder:

> Before each game, the contents of the server-side read directory for your bot are copied to the client machine under 'bwapi-data/read/'. For the first round of the tournament this directory will be blank since a full round has not yet been played.

[StarcraftAITournamentManager](https://github.com/davechurchill/StarcraftAITournamentManager) asks you whether to clear the read folders when you start a new run or do a rerun.

I know the SSCAIT competition allows users to upload their own read folder separately to the bot binaries, so it's probably not a problem for SSCAIT, but it would be good if it would work out of the box for AIIDE/CIG or anything that uses [StarcraftAITournamentManager](https://github.com/davechurchill/StarcraftAITournamentManager).

I notice there is also a mapData folder. Is this simply an identical copy from BWTA2? If so then why not simply use the same path as BWTA2 instead of needing a whole other copy? if it is different, why isn't it under the "bwapi-data/" folder? Whatever you think is easiest for competition organizers to manage is best.

The mapData folder could also be affected by this issue, assuming they are static, but I assume map data files like BWTA2 is treated specially by StarcraftAITournamentManager because the competition organizers decide what maps will be used in the competition - not the developers of the bots.

**Comment by Ravaelles** [comment]
Hey, Chris! Thank you for your very valuable issue. You're absolutely right about `bwapi-data/AI` and that build orders should be inside it. I will change it in the next release. Really appreciate you mention it, because it shows to me that this project isn't just a playground for me and 1-2 more people, but that it can become a significant tool in writing serious bots.

And about the `mapData` folder. It is created by BWMirror 2.5 (I think) so I don't have influence on it. So the files (and entire dir?) are generated automatically if they're not found. I might be able to recompile BWMirror's source and change the location to `bwapi-data/AI/mapData`. Not sure if it's possible. Also I prefer to make the least possible changes to BWMirror so I don't basically maintain my own version of it, compatible with Atlantis. I will ask Michal Certicky about it, he should know if it's a problem or not.

By the way: love to talk to the author of such a good bot like ZZZBot. There're few bots who are really nice to watch and your is definitely one of them.

**Comment by Ravaelles** [comment]
Actually it turned out that `mapData` was a junk folder that left behind JNIBWAPI (which we don't use anymore), so I've just removed it. Thanks for this tip as well :- )

**Comment by chriscoxe** [comment]
Happy to help, and kind of you to say.  Good initiative with this project - as you know it is hard to get started writing a bot without something like this as a starting point.  I stopped working on my bot last year but recently I've been wondering whether I should get back into BW botting, what with all the DeepMind news (although according to the latest news it appears they may be planning an AI just for SC2 not BW).  What I wrote before was throw-away code and so I was curious about your project.  Not sure whether I'll write another BW bot but you never know.  Maybe I'll have a go at SC2.
