### ISSUE TITLE
Allow to select enemy building positions in Select

### ISSUE THREAD

**Issue by certicky** [Ravaelles/Atlantis#7]
I think that Atlantis should implement some sort of "memory" for previously seen enemy buildings. Simply maintain a set of positions at which we've seen some enemy buildings, so that we have some attack targets to choose from. The Select class might have the **enemyBuildingPositions()** method.

Maintaining such set shouldn't be hard. You simply add a position to it every time you see an enemy building and remove it every time you see that position and the expected building is not there any more (meaning that it's been destroyed of lifted/moved).

**Comment by Ravaelles** [comment]
That is already implemented (remembering positions of enemy buildings, class AtlantisEnemyUnits), it's just not possible to be accessed via Select class. That's why I want to introduce FoggedUnit class, which will make it possible, because Select should always return units.

It's one of solutions that exist, but are temp solutions and should be improved. Atlantis 1.0 version should have all the things I want, every release <1.0 should be treated as a work in progress, however usable and easily extendable. I'm simply changing a lot of things to adapt it to large scale solutions :)

I don't have ETA for this Select feature, but will be steadily working on it in free time :)

**Comment by Ravaelles** [comment]
`EnemyUnits` class now stores information about "fogged units".

It can be used like this: https://github.com/Ravaelles/Atlantis/blob/1b23ee66ff601f67b20e550c62df6eacb2cfaf16/src/atlantis/enemy/EnemyInformation.java#L213
